# Generated by Django 5.0.7 on 2024-07-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(max_length=250, verbose_name='description')),
                ('url', models.URLField(verbose_name='url')),
                ('published_at', models.DateTimeField(verbose_name='date')),
            ],
        ),
    ]
